/**
 * One icon family for the whole app (Phosphor), re-exported from the SSR build
 * so the same names work in server and client components. Default weight is
 * normalised here rather than at each call site.
 */
import type { IconProps } from "@phosphor-icons/react/dist/lib/types";
import {
  ArrowCounterClockwise,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUpRight,
  ArrowsClockwise,
  Bell,
  BookmarkSimple,
  BookOpen,
  CalendarBlank,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChartBar,
  ChatCircle,
  Check,
  CheckCircle,
  Clock,
  ClockCounterClockwise,
  Compass,
  Copy,
  DiceFive,
  DotsThreeVertical,
  Eye,
  EyeSlash,
  Fire,
  Flag,
  FolderOpen,
  Funnel,
  Gear,
  GitDiff,
  Globe,
  Hash,
  Heart,
  House,
  Image,
  Info,
  Lightbulb,
  Link,
  List,
  Lock,
  LockOpen,
  MagnifyingGlass,
  MapPin,
  Megaphone,
  Moon,
  NotePencil,
  PaperPlaneTilt,
  PencilSimple,
  Plus,
  Prohibit,
  Quotes,
  Scroll,
  SealCheck,
  ShieldCheck,
  SignIn,
  SignOut,
  Sparkle,
  SpinnerGap,
  SquaresFour,
  Star,
  Sun,
  Tag,
  TextAa,
  ThumbsUp,
  Trash,
  UploadSimple,
  User,
  Users,
  Warning,
  WarningCircle,
  WarningOctagon,
  X,
} from "@phosphor-icons/react/dist/ssr";

function withDefaults(Icon: React.ComponentType<IconProps>) {
  function Normalized(props: IconProps) {
    return <Icon weight="regular" {...props} />;
  }
  Normalized.displayName = Icon.displayName ?? "Icon";
  return Normalized;
}

export const Icons = {
  search: withDefaults(MagnifyingGlass),
  random: withDefaults(DiceFive),
  shuffle: withDefaults(SquaresFour),
  popular: withDefaults(Fire),
  clock: withDefaults(Clock),
  star: withDefaults(Star),
  verified: withDefaults(SealCheck),
  check: withDefaults(Check),
  checkCircle: withDefaults(CheckCircle),
  eye: withDefaults(Eye),
  eyeOff: withDefaults(EyeSlash),
  edit: withDefaults(PencilSimple),
  note: withDefaults(NotePencil),
  tag: withDefaults(Tag),
  hash: withDefaults(Hash),
  category: withDefaults(FolderOpen),
  plus: withDefaults(Plus),
  warning: withDefaults(Warning),
  warningCircle: withDefaults(WarningCircle),
  warningOctagon: withDefaults(WarningOctagon),
  flag: withDefaults(Flag),
  bell: withDefaults(Bell),
  heart: withDefaults(Heart),
  bookmark: withDefaults(BookmarkSimple),
  user: withDefaults(User),
  users: withDefaults(Users),
  signIn: withDefaults(SignIn),
  signOut: withDefaults(SignOut),
  sun: withDefaults(Sun),
  moon: withDefaults(Moon),
  menu: withDefaults(List),
  close: withDefaults(X),
  caretDown: withDefaults(CaretDown),
  caretLeft: withDefaults(CaretLeft),
  caretRight: withDefaults(CaretRight),
  arrowLeft: withDefaults(ArrowLeft),
  arrowRight: withDefaults(ArrowRight),
  arrowUpRight: withDefaults(ArrowUpRight),
  external: withDefaults(ArrowSquareOut),
  shield: withDefaults(ShieldCheck),
  lock: withDefaults(Lock),
  lockOpen: withDefaults(LockOpen),
  trash: withDefaults(Trash),
  revert: withDefaults(ArrowCounterClockwise),
  diff: withDefaults(GitDiff),
  history: withDefaults(ClockCounterClockwise),
  chart: withDefaults(ChartBar),
  settings: withDefaults(Gear),
  logs: withDefaults(Scroll),
  home: withDefaults(House),
  info: withDefaults(Info),
  link: withDefaults(Link),
  upload: withDefaults(UploadSimple),
  media: withDefaults(Image),
  spinner: withDefaults(SpinnerGap),
  ban: withDefaults(Prohibit),
  sparkle: withDefaults(Sparkle),
  filter: withDefaults(Funnel),
  refresh: withDefaults(ArrowsClockwise),
  copy: withDefaults(Copy),
  send: withDefaults(PaperPlaneTilt),
  more: withDefaults(DotsThreeVertical),
  megaphone: withDefaults(Megaphone),
  quote: withDefaults(Quotes),
  book: withDefaults(BookOpen),
  compass: withDefaults(Compass),
  thumbsUp: withDefaults(ThumbsUp),
  calendar: withDefaults(CalendarBlank),
  pin: withDefaults(MapPin),
  globe: withDefaults(Globe),
  chat: withDefaults(ChatCircle),
  lightbulb: withDefaults(Lightbulb),
  text: withDefaults(TextAa),
};

export type IconName = keyof typeof Icons;
